image: node

stages:
  - lint
  - build
  - publish
  - deploy

lint:
  stage: lint
  tags:
    - docker
  script:
    - npm i
    - npm run lint

build:
  stage: build
  tags: 
    - docker
  script:
    - npm i
    - npm run build

publish:
  image: docker:latest
  stage: publish
  tags:
    - docker-build
  services:
    - name: docker:dind
  script: 
    - docker build . -t uniprojects/dentigo-booking-service
    - docker login -u uniprojects -p $DOCKER_PASSWORD
    - docker push uniprojects/dentigo-booking-service
  environment:
    name: production
  only:
    refs:
      - main

deploy:
  stage: deploy
  tags:
    - docker
  image: docker:latest
  script:
    - eval $(ssh-agent -s)
    - chmod og= $SSH_PRIVATE_KEY
    - ssh-add $SSH_PRIVATE_KEY
    - mkdir -p ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - chmod 700 ~/.ssh
    - docker -H $SSH_URL compose down --remove-orphans
    - docker -H $SSH_URL compose pull
    - docker -H $SSH_URL compose up -d
  environment:
    name: production
  only:
    refs:
      - main

